// ARTICLES
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAIL = 'FETCH_ARTICLES_FAIL';
export const FETCH_ARTICLE_DETAILS = 'FETCH_ARTICLE_DETAILS';
export const FETCH_ARTICLE_DETAILS_SUCCESS = 'FETCH_ARTICLE_DETAILS_SUCCESS';
export const FETCH_ARTICLE_DETAILS_FAIL = 'FETCH_ARTICLE_DETAILS_FAIL';

// CATEGORIES
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES';
